scrape_configs:
  # Scrape Prometheus server's own metrics
  - job_name: "prometheus"
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["localhost:9090"]

  # Scrape FastAPI app metrics
  - job_name: "fastapi"
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["web:8000"]   # "web" is the Docker service name, or replace with host:port